version: "3.8"
services:
  database_server:
    image: mcr.microsoft.com/mssql/server
    restart: always
    env_file:
      - variables.env
    ports:
      - target: 1433
        published: 1434
        protocol: tcp
        mode: host
  web_server:
    build:
      dockerfile: Dockerfile-webserver
    restart: always
    env_file:
      - variables.env
    depends_on:
      - database_server
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - ./applicatie/:/applicatie/
      - ./webserver-setup/:/setup/
    entrypoint: [ "sh", "/setup/bootstrap.sh" ]
    secrets:
      - source: password_rdbms_app
        uid: '0'
        gid: '0'
        mode: 0440
secrets:
  password_rdbms_app:
    file: password_rdbms_app.txt